dist: trusty

language: python

python:
    - '2.7'
    - '3.6'

addons:
  apt:
    packages:
      - pandoc

before_install:
  - pip install pytest pytest-cov pylint

install:
  - pip install .

script:
  - pylint betterbib
  - pylint test/*.py
  - pylint tools/betterbib
  - pylint tools/bibitems2bibtex
  # cd into test directory to make sure we're using the pip-installed
  # betterbib.
  - cd test && pytest --cov betterbib

after_success:
  - bash <(curl -s https://codecov.io/bash)
