#sudo: false
sudo: required
dist: trusty

language: python

python:
    - "2.7"
    - "3.4"

virtualenv:
  system_site_packages: true

# install dependencies
addons:
  apt:
    packages:
      - pandoc
      - python-requests
      - python3-requests

before_install:
  - pip install -r requirements.txt
  - pip install pytest-cov

install:
  # Alternative: setup.py install.
  # Using pip makes sure that the package is pip-compatible, too.
  - pip install .

# run tests
script:
  # cd into test directory to make sure we're using the pip-installed
  # betterbib.
  - cd test
  - pytest --cov betterbib

after_success:
  - bash <(curl -s https://codecov.io/bash)
