dist: trusty

language: python

python:
    - '2.7'
    - '3.4'

addons:
  apt:
    packages:
      - pandoc

before_install:
  - pip install pytest pytest-cov

install:
  - pip install .

script:
  # cd into test directory to make sure we're using the pip-installed
  # betterbib.
  - cd test && pytest --cov betterbib

after_success:
  - bash <(curl -s https://codecov.io/bash)
