#sudo: false
sudo: required
dist: trusty

language: python

python:
    - "2.7"
    - "3.4"

virtualenv:
  system_site_packages: true

# install dependencies
addons:
  apt:
    packages:
      - pybtex
      - python-bs4
      - python3-bs4
      - python-lxml
      - python3-lxml
      - python-requests
      - python3-requests

install:
  - pip install -r requirements.txt
  - pip install coveralls
  # Alternative: setup.py install.
  # Using pip makes sure that the package is pip-compatible, too.
  - pip install .

# run tests
script:
  - nosetests --with-coverage --cover-package=betterbib

after_success:
  - coveralls
