version: 2

jobs:
  lint:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt update
      - run: apt install -y python3-pip
      - run: pip3 install -U black flake8
      - run: LC_ALL=C.UTF-8 black --check setup.py matplotlib2tikz/ test/*.py
      - run: flake8 setup.py matplotlib2tikz/ test/*.py
  build:
    working_directory: ~/work
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt update
      - run: apt install -y git python3-pip enchant
      - run: pip3 install -U pytest pytest-cov
      - checkout
      - run: pip3 install .
      # add some entries to the dict
      - run: mkdir -p ~/.config/betterbib/ && echo -e "[DICTIONARY]\nadd=Magnus,Peano,Kutta,Runge,Hermitian,Jacobian\nremove=hermitian" > ~/.config/betterbib/config.ini
      # The tests
      - run: cd test/ && pytest --maxfail=1 --cov betterbib
      # submit to codecov
      - run: apt install -y curl
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
